#!/usr/bin/bash
cmdpath='/cmds/'
cmdname="$1"

# if we're using git commands
if [ "$1" = "git" ]
  then
    cmdpath='/cmds/git/'
    cmdname="$2"
fi

# if passed a command
if [ $cmdname ]
  # check if it was passed a specific flag here
  then
    if [ -e ".$cmdpath$cmdname" ]
      then
        ".$cmdpath$cmdname"
    else
      echo -e 'Error:' \'$cmdname\' 'command not found.'
      exit 1
    fi
else
  echo -e '\n\tTEACHME PROGRAM'
  echo -e '\n\tThe purpose of teachme is to provide beginner-friendly explanations\n\tto command-line and git topics and commands'
  echo -e '\tSee which topics are available to learn by typing ./teachme --list'
  echo -e '\n\tteachme usage:\n'
  echo -e '\tteachme <topic>'
fi



