#!/usr/bin/bash
cmdpath='/cmds/'
cmdname="$1"
# flags are read first

if [ "$1" = "--help" ]
  then ./help
  exit 0
fi

if [ "$1" = "--list" ]
  then ./list
  exit 0
fi

# if we're using git commands
if [ "$1" = "git" ]
  then
    cmdpath='/cmds/git/'
    cmdname="$2"
fi

# if passed a command
if [ $cmdname ]
  # check if it was passed a specific flag here
  then
    if [ -e ".$cmdpath$cmdname" ]
      then
        ".$cmdpath$cmdname"
    else
      echo -e 'Error:' \'$cmdname\' 'command not found.'
      exit 1
    fi
else
  ./help
  exit 0
fi



