#!/usr/bin/bash
echo "This is a git add command."

# The command's name
echo -e 'git add'

# the command's description
echo "The command add file cotents to the index."
echo "git add updates the index with the current content found in the working tree, to prepare staged changes for commit."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
