#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git branch develop-branch"
echo "git checkout develop-branch"
echo "Creat a branch named develop-branch, and switch to develop-branch from current branch."

# example 2
echo "git branch -d develop-branch"
echo "delete branch develop-branch, provided that the branch is fully merged in its upstream branch, or in HEAD if no upstream was set."


exit 0
