#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git checkout [options] <branch>"
echo -e "\t-b <new_branch>: creat a new branch."
echo -e "\t-q: queit, supress feedback messages.
echo -e "\t-t --track: when creating a new branch, setting up upstream configuration."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
