#!/usr/bin/bash
echo "This is a git commit command."

# The command's name
echo -e 'git commit'

# the command's description
echo "Stores the current contents of the index in a new commit along with a commit message describing the changes made.
ehco "A commit is a snapshot of the current state of the repository, if you make a commit and then find a mistake in it, you may retrieve the commit with git reset."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
