#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git diff"
echo "Shows difference between commits, commit and working tree or index, etc"

# example 2
echo "git diff branch master"
echo "Shows changes between the current branch and the master branch."

echo "git diff --name-status"
echo "Shows only name and nature of the change, but not actual diff output."

exit 0
