#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git fetch [options] [repository]"
echo -e "\t--all: fetch all remotes."
echo -e "\t-k: keep downloaded pack."
echo -e "\t-b: be verbose."
echo -e "\t-a: append downloaded object and refs to the existing repository file, without this flag, the current file will be overwritten."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
