#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "cd /path/to/my/repo"
echo "git init"
echo "git add -A"
echo "git commit"
echo "Creat a /path/to/my/repo/.git directory, add all existing files to the staging area, the first commit in this repo's hitory record its initial state."

exit 0
