#!/usr/bin/bash
echo "This is a git merge command."

# The command's name
echo -e 'git merge'

# the command's description
echo "Join two or more development history together, it can be used to incorporates changes from the named commits,changes from another repository or branch into the current branch."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
