#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git pull [options] [<repository>[<refspec>...]]"
echo -e "\t-all: fetch all branches."
echo -e "\t-a: a stands for append, append ref names and object names."
echo -e "\t-k: keep download pack."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
