#!/usr/bin/bash
echo "This is a git rebase command."

# The command's name
echo -e 'git rebase'

# the command's description
echo "The rebase command take all the changes that were commited on one branch and replay them on another one."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
