#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git reset <file>"
echo "Remove the specified file from the staging area."
echo "git reset"
echo "Reset the staging area to the most recent commit."
echo "git reset <commit>"
echo "Reset the current branch tip backward to <commit>, reset the staging area to match, but leaves the working directory alone. All changes made since <commit> will reside in the working directory."
echo "git reset --hard>
echo "Reset both the staging area and the working directory to the most recent reset.""
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
