#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git rm [options] <file>..."
echo "git rm options"
echo -e "\t-f, --force, override the current up-to-date check."
echo -e "\t-r, Recursive deletion when a directory is given."
echo -e "\t-n, --dry-run, Don't actually remove any file(s). Instead, just show if they exist in the index and would otherwise be removed by the command.
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
