#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git status [options]..."
echo "git status -s"
echo "Give the output in short format."
echo "git status -b"
echo "Show the branch and tracking info even in short-format."
echo "git status -long"
echo "Gvie the output in long-format."
echo "git status -v"
echo "'v' stands for verbose, gives more detailed output."
echo "git status --ignored"
echo "Show ignored files as well."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
