#!/usr/bin/bash
echo "This is a chmod command."

# The command's name
echo -e 'chmod'

# the command's description
echo "The chmod utility changes file mode, grant or deny write, read, execute permissions to users, groups and others."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
