#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "cp [option]... source... directory"
echo "cp [option]... source target"
echo "cp -f: The f flag means force, removes the target file if it can not opened for write operations."
echo "cp -H: Tell the cp command to follow symbolic links."
echo "cp -i: Interactive, prompts for confirmation when overwritting a target file."
echo "cp -r: copy directories recursively."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
