#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "curl [options] url"
echo "curl -o google.html http://www.google.com"
echo "curl http://www.google.com and save the result of the command to a file named google.html."
echo "curl -v http://www.google.com"
echo "Enable the verbose mode and more details will be printed to the screen."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
