#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "echo [OPTION]... string"
echo "echo -n string"
echo "Do not print trailing newline to the screen."
echo "echo -e string"
echo "Enable interpretation of backslash escape sequences such as \n(newline), \b(backspace), \e(the escape character)..."
echo "echo -E string"
echo "Disable interpretaion of backslash escape sequences."
echo "echo --help"
echo "Print a help message and exit."
echo "echo --version"
echo "Print version information and exit."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
