#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "find . -type f -name *.txt"
echo "Find all files with .txt file extension in the current directory and subdirectories."

# example 2
echo "find .type -f -exec ls -s {} \;" | sort -n -r | tail -1
echo "Find recurse through the file hierachy, list and sort the files and display the smallest file it finds."


exit 0
