#!/usr/bin/bash
echo "This is a for command."

# The command's name
echo -e 'for'

# the command's description
echo "For loops allow you to iterate through items in an array or other list one at a time until you complete the list. As you move from one item to the next in the list, you can take action on the item."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
