#!/usr/bin/bash

# The command's name
echo -e 'grep'

# the command's description
echo "grep, which stands for 'global regular expression', allows you to search one file or multiple files for lines that contain a pattern."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
