#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "man [options] name..."
echo "man ls"
echo "Display the manual page for 'ls' command."
echo "man -f ls" 
echo "Display a short description from the command's man page, if available."
echo "man -a ls"
echo "Force man to display all manual pages instead of just the one it finds most suitable."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
