#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "mkdir -m 777 mydir"
echo "Creat a directory named mydir with all types of permissions enabled for all users."

# example 2
echo "mkdir -p sport/team_play/basketball"
echo The -p (i.e., parents) option creates the specified intermediate directory if it doesn't exist.


exit 0
