#!/usr/bin/bash

# The command's name
echo -e 'ping'

# the command's description
echo "The command ping can be used to test if a remote server is up and running. The ping command sends ICMP Echo Request packets to the host once per second. Each packet that is echoed back via an ICMP Echo Response packet is written to the standard output."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
