#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "ls -lS | wc -l"
echo "List files in working directory in long format by file size, pipe the result of ls command to wc and print the line numbers to screen."

# example 2
echo "lsof | more"
echo "list all optn files and pass the list to more to display it one screen at a time."


exit 0
