#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'rm'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "rm -r mydir"
echo "Instead using mkdir, when a directory is not empty, you need to use the recursive flag with rm to complete delete a directory."

# example 2
echo "rm *"
echo "Remove all files in the working directory."

echo "rm -i *"
echo "prompt for comfirmation before removing every files in the working directory."


exit 0
