#!/usr/bin/bash
echo "This is a rmdir command."

# The command's name
echo -e 'rmdir'

# the command's description
echo "The rmdir command removes each specified directory, provided the directory is empty. If a directory is not empty, you may need to use the rm command with the recursive flag -r enabled to delete the directory."
echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
