#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "ssh"
echo "ssh vito_fan@epacket.com"
echo "epacket.com is the URL you want to connect to, vito_fan is the username, before you're connected to the server, the password is required to be entered and authenticated."

exit 0
