#!/usr/bin/bash

# The command's name
echo -e 'tar'

# the command's description
echo "'tar' stands for tape archive. It is used to collect, distribute and archive files, while preseving file system attributes such as owner user and group permissions, access and modification dates, and directory structures."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
