#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "sudo [option] command"
echo "-l: list commands allowed and forbidden for the user on the current host."
echo "-h: help option cause sudo to print a usage message and exit."
echo "-k: the kill option sudo invalidates the user's timestamp."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
