#!/usr/bin/bash

# The command's name
echo -e 'touch'

# the command's description
echo "Touch changes file timestamps, updates the access and modification times of each files to current system time. If the specified file does not already exist, touch will create a new file with that filename."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
