#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "ls -l | wc -lw"
echo "Prints the line and word count of the standard output of ls -l."

# example 2
echo "wc myfile.txt"
echo "Display information regarding number of lines, number of words 
and number of characters of the file myfile.txt"


exit 0
