#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "#!/usr/bin/env/ bash"
echo "a=0"
echo -e "\twhile [ $a -lt 5 ]"
echo "do"
echo -e "\techo $a""
echo -e "\tlet a=a+1"
echo "done"
echo "The while loop prints 0 to 5 to the screen."

echo "The until loop functions in manner opposite to while loop, it will stop the moment the conditional evaluates to true."
echo "#!/usr/bin/env bash"
echo "a=0"
echo -e "\tuntil [ $a -eq 5 ]"
echo "do"
echo -e "\techo "$a""
echo -e "\tlet a=a+1"
echo "done"
exit 0
